### ISSUE TITLE
"Error: Unknown permission pass error" on CI (Jenkins)

### ISSUE THREAD

**Issue by nikolaykasyanov** [wix/AppleSimulatorUtils#15]
#### Description

AppleSimulatorUtils fails on CI with "Error: Unknown permission pass error" error. I'm using Jenkins.

Here's the command I use:

```bash
$ applesimutils --simulator "iPhone 7, OS=11.0" --bundle my.bundle.id --setPermissions "location=inuse, notifications=YES"
```

Although when I login to the build node through SSH this command works perfectly.

#### Steps to Reproduce

1. add applesimutils call to build script & push
2. make CI build it

#### Device, macOS and Xcode Versions

macOS version: 10.12.6
Xcode version: 9.0.1
Simulator: iPhone 7, OS=11.0

**UPD:** I've just tried it on GitLab CI, got the same error.
**UPD 2:** If `notifications=YES` permission is removed from the command, it works.

**Comment by nikolaykasyanov** [comment]
I investigated a bit and it seems that [`[fileManager fileExistsAtPath:versionedSectionInfoPath]`](https://github.com/wix/AppleSimulatorUtils/blob/beacf76827de0ffc9656b8c46913ff4518664230/applesimutils/applesimutils/SetNotificationsPermission.m#L65) call returns `NO` even though a file at the path exists.

Any ideas what can cause this?

**Comment by nikolaykasyanov** [comment]
I added `cat <path to versioned section info file>` to my build script to check if it could be permission/sandboxing/etc issue but it works flawlessly. No idea what might cause `NSFileManager` to misbehave.

**Comment by nikolaykasyanov** [comment]
Actually, location permission might be failing as well because it [doesn't check](https://github.com/wix/AppleSimulatorUtils/blob/beacf76827de0ffc9656b8c46913ff4518664230/applesimutils/applesimutils/SetLocationPermission.m#L75) whether file has been written successfully or not.

**Comment by LeoNatan** [comment]
Could be that the test user Jenkins uses does not have permission to access this location—that’s a problem. Could you please see if you can elevate the user’s permissions?

**Comment by nikolaykasyanov** [comment]
It seems like Fastlane is the culprit. When I run the command outside of it, it works. Sorry for the false alarm.

**Comment by LeoNatan** [comment]
Cheers

**Comment by nikolaykasyanov** [comment]
Well, it's not even Fastlane. The problem is that I'm erasing simulator before each CI build (with `xcrun simctl erase` command), thus making `%SIMUUID%/data/Library` folder empty, making it impossible for AppleSimUtils to write files without creating intermediate directories explicitly.

I'd say this is an important CI scenario to support, what do you think?

**Comment by someTestAccount1** [comment]
I came across this project an hour ago as parallel UITests cannot handle dismissing OS alerts on multiple devices it seems. Looks like a great solution to some simulator issues, thanks for sharing.

I can confirm that when I run the command passing in that permission it fails every time. Running it locally with needed permissions.

applesimutils --simulator $2 --bundle com.apple.test.$1-Runner --setPermissions "notifications=YES"

**Comment by LeoNatan** [comment]
The utility is supposed to handle that by silently booting the simulator before attempting to do what it does. `erase` does `Reset content and settings` right? I will try this scenario, thanks for reporting.

**Comment by LeoNatan** [comment]
Also, I don't like this `Unknown permission pass error` error message. Somehow, no error object has propagated, which is not good. Will try to improve that also.

**Comment by LeoNatan** [comment]
Fixed. The issue was improper handling of the first-time boot. Now, `applesimutils` properly awaits the boot process to finish before continuing with the rest of the permission modifications.

**Comment by someTestAccount1** [comment]
Thanks for fixing. I set notifications=YES  but still get the alert when the tests run. Im using parallel tests (multiple destinations) and set permissions on all the simulators. For some reason the interruptMonitors and setting it via applesimutils doesn't dismiss the alert on all sims, only one? Have you come across this issue?

**Comment by nikolaykasyanov** [comment]
@LeoNatan thanks a lot, works great!

**Comment by LeoNatan** [comment]
@someTestAccount1 Not, I am not familiar with this issue. Are you sure you are running correctly for each simulator?

**Comment by someTestAccount1** [comment]
Hi, yes, I set the permissions on each simulator before running the tests. I notice the issue when not using applesimutils too, alerts only dismiss on one device. Have you guys successfully dismissed alert popups when running a ui test on multiple destinations at once?

**Comment by LeoNatan** [comment]
We don't support that yet, so we haven't hit such a problem. I am not sure why it should happen. Could you please elaborate more on how you dispatch commands to your simulators?

**Comment by someTestAccount1** [comment]
Currently its a script that finds a deletes the needed simulators, recreates them, applies permissions to each created simulator using the ID, then calls xcodebuild passing in a number of simulators as destinations. Whether applying permissions or not, the interruptMonitor handler is only triggered on one of the simulators in a parallel test. This might be a bug in XCTest, I will raise one if others have the same issue.
